title: <p align="center"> Vinod Kumar </p>
logo: /assets/img/my-profile-pic.jpeg
description: <div align="center">
  <a href="./assets/pdf/Resume-Vinod.pdf">Resume</a> |
  <a href="https://linkedin.com/in/vinod19">LinkedIn</a> |
  <a href="https://github.com/vvinod64">GitHub</a>
   </div>
  <div align="center">
    I'm learner of Artifical Inteligence/Machine Learning.
    I have gained exposure to Big Data technologies, such as Apache Spark and Cassandra.
    I am passionate about creating robust, high-quality software systems and have a strong enthusiasm for continuous learning, keeping up with the latest in technology trends.
  </div>
  
theme: jekyll-theme-minimal
